"""State generic-substitution law (SPEC §20): curated, statute-cited.

Every US state (plus DC) regulates whether a pharmacist MAY or MUST
substitute an FDA-rated equivalent generic, whether the patient must
consent or be notified, and how a prescriber blocks substitution. The
note page (§18) uses this to replace "in most states" with the actual
rule for the reader's state.

Curation rules:
- Every row cites the primary STATUTE (public domain) with a working
  URL to the statute text. The classification layer additionally cites
  Sacks et al., JAMA Internal Medicine 2020 (open access) and the CT
  OLR 2013-R-0071 50-state table — never NABP's license-restricted
  survey.
- A row that could not be verified against the statute or two agreeing
  citable secondary sources ships substitution='unverified' and the UI
  falls back to the generic sentence — never guessed.
- `as_of` is the research access date, always rendered. Rendered
  language always carries the DISCLAIMER constant ("Not legal
  advice - the statute text controls").

This is REFERENCE information about public law, not pipeline data —
served by the API (no DB dependency), rendered by the note page.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Any

SUBSTITUTION_KINDS = ("mandatory", "permissive", "unverified")


@dataclass(frozen=True)
class StateRule:
    state: str  # USPS code
    name: str
    substitution: str  # 'mandatory' | 'permissive' | 'unverified'
    patient_consent_required: bool | None  # None = unknown
    patient_notification_required: bool | None
    patient_may_refuse: bool | None
    prescriber_override: str  # exact mechanism, one line
    statute_citation: str
    statute_url: str
    as_of: str  # YYYY-MM-DD research access date


DISCLAIMER = (
    "Not legal advice - the statute text controls. Classification per "
    "the cited statute; layer cross-checked against Sacks et al., JAMA "
    "Internal Medicine 2020 (open access) and Connecticut OLR report "
    "2013-R-0071."
)

# Populated by the recorded research pass (docs/dossiers/
# 2026-08-statelaw-research.md is the evidence for every row).
STATE_RULES: tuple[StateRule, ...] = (
    StateRule(
        state='AL',
        name='Alabama',
        substitution='permissive',
        patient_consent_required=False,
        patient_notification_required=False,
        patient_may_refuse=None,
        prescriber_override="Prescriber signs the 'dispense as written' line on the two-signature-line form; oral or electronic instruction",
        statute_citation='Ala. Code § 34-23-8',
        statute_url='https://law.justia.com/codes/alabama/title-34/chapter-23/article-1/section-34-23-8/',
        as_of='2026-08-14',
    ),
    StateRule(
        state='AK',
        name='Alaska',
        substitution='permissive',
        patient_consent_required=True,
        patient_notification_required=None,
        patient_may_refuse=True,
        prescriber_override="Prescription indicates 'to be dispensed only as written'",
        statute_citation='Alaska Stat. § 08.80.295',
        statute_url='https://codes.findlaw.com/ak/title-8-business-and-professions/ak-st-sect-08-80-295.html',
        as_of='2026-08-14',
    ),
    StateRule(
        state='AZ',
        name='Arizona',
        substitution='permissive',
        patient_consent_required=False,
        patient_notification_required=False,
        patient_may_refuse=None,
        prescriber_override="'DAW', 'dispense as written', 'do not substitute', 'medically necessary' or clear equivalent on the face of the prescription",
        statute_citation='A.R.S. § 32-1963.01',
        statute_url='https://www.azleg.gov/ars/32/01963-01.htm',
        as_of='2026-08-14',
    ),
    StateRule(
        state='AR',
        name='Arkansas',
        substitution='permissive',
        patient_consent_required=False,
        patient_notification_required=False,
        patient_may_refuse=True,
        prescriber_override='Prescriber in own handwriting indicates no substitution by name or initial; express indication otherwise',
        statute_citation='Ark. Code Ann. § 17-92-503',
        statute_url='https://codes.findlaw.com/ar/title-17-professions-occupations-and-businesses/ar-code-sect-17-92-503.html',
        as_of='2026-08-14',
    ),
    StateRule(
        state='CA',
        name='California',
        substitution='permissive',
        patient_consent_required=False,
        patient_notification_required=True,
        patient_may_refuse=None,
        prescriber_override="Orally or in own handwriting 'Do not substitute', or preprinted box personally initialed; e-prescription notation needs no initials",
        statute_citation='Cal. Bus. & Prof. Code § 4073',
        statute_url='https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=BPC&sectionNum=4073',
        as_of='2026-08-14',
    ),
    StateRule(
        state='CO',
        name='Colorado',
        substitution='permissive',
        patient_consent_required=False,
        patient_notification_required=True,
        patient_may_refuse=None,
        prescriber_override="Initial or sign the 'dispense as written'/'DAW'/'do not substitute' box (hand or electronic; no preprinted initials); oral",
        statute_citation='C.R.S. § 12-280-125',
        statute_url='https://codes.findlaw.com/co/title-12-professions-and-occupations/co-rev-st-sect-12-280-125.html',
        as_of='2026-08-14',
    ),
    StateRule(
        state='CT',
        name='Connecticut',
        substitution='permissive',
        patient_consent_required=False,
        patient_notification_required=True,
        patient_may_refuse=True,
        prescriber_override="Handwrite 'BRAND MEDICALLY NECESSARY' (may not be preprinted or stamped)",
        statute_citation='Conn. Gen. Stat. § 20-619',
        statute_url='https://www.cga.ct.gov/current/pub/chap_400j.htm#sec_20-619',
        as_of='2026-08-14',
    ),
    StateRule(
        state='DE',
        name='Delaware',
        substitution='permissive',
        patient_consent_required=False,
        patient_notification_required=True,
        patient_may_refuse=None,
        prescriber_override="Withhold the 'substitution permitted' authorization, or handwrite 'Brand Necessary'/'Brand Medically Necessary'",
        statute_citation='24 Del. C. § 2550',
        statute_url='https://delcode.delaware.gov/title24/c025/sc07/index.html',
        as_of='2026-08-14',
    ),
    StateRule(
        state='DC',
        name='District of Columbia',
        substitution='permissive',
        patient_consent_required=False,
        patient_notification_required=True,
        patient_may_refuse=True,
        prescriber_override="Own-handwriting 'dispense as written'/'D.A.W.' on the signed prescription (preprinted box invalid); oral statement noted",
        statute_citation='D.C. Code §§ 48-803.02 to 48-803.03a',
        statute_url='https://code.dccouncil.gov/us/dc/council/code/sections/48-803.02',
        as_of='2026-08-14',
    ),
    StateRule(
        state='FL',
        name='Florida',
        substitution='mandatory',
        patient_consent_required=False,
        patient_notification_required=True,
        patient_may_refuse=True,
        prescriber_override="Written: 'MEDICALLY NECESSARY' in the prescriber's own handwriting; oral: express statement; e-prescription: overt act",
        statute_citation='Fla. Stat. § 465.025',
        statute_url='https://www.leg.state.fl.us/statutes/index.cfm?App_mode=Display_Statute&URL=0400-0499/0465/Sections/0465.025.html',
        as_of='2026-08-14',
    ),
    StateRule(
        state='GA',
        name='Georgia',
        substitution='permissive',
        patient_consent_required=False,
        patient_notification_required=False,
        patient_may_refuse=True,
        prescriber_override="'Brand necessary' in the body of the prescription, in own handwriting on paper (no print or stamp); any method electronically",
        statute_citation='O.C.G.A. § 26-4-81',
        statute_url='https://codes.findlaw.com/ga/title-26-food-drugs-and-cosmetics/ga-code-sect-26-4-81.html',
        as_of='2026-08-14',
    ),
    StateRule(
        state='HI',
        name='Hawaii',
        substitution='mandatory',
        patient_consent_required=False,
        patient_notification_required=True,
        patient_may_refuse=True,
        prescriber_override="Handwrite 'brand medically necessary' (not preprinted or stamped); oral or electronic equivalent",
        statute_citation='Haw. Rev. Stat. § 328-92',
        statute_url='https://www.capitol.hawaii.gov/hrscurrent/Vol06_Ch0321-0344/HRS0328/HRS_0328-0092.htm',
        as_of='2026-08-14',
    ),
    StateRule(
        state='ID',
        name='Idaho',
        substitution='permissive',
        patient_consent_required=False,
        patient_notification_required=False,
        patient_may_refuse=None,
        prescriber_override='Prescriber orders that a brand name drug shall be dispensed - then no drug product selection is permitted',
        statute_citation='Idaho Code § 54-1733B (2025)',
        statute_url='https://legislature.idaho.gov/statutesrules/idstat/Title54/T54CH17/SECT54-1733B/',
        as_of='2026-08-14',
    ),
    StateRule(
        state='IL',
        name='Illinois',
        substitution='permissive',
        patient_consent_required=False,
        patient_notification_required=False,
        patient_may_refuse=None,
        prescriber_override="In own handwriting place a mark beside 'may not substitute' plus hand signature (preprinted or rubber-stamp marks void)",
        statute_citation='225 ILCS 85/25',
        statute_url='https://www.ilga.gov/Documents/legislation/ilcs/documents/022500850K25.htm',
        as_of='2026-08-14',
    ),
    StateRule(
        state='IN',
        name='Indiana',
        substitution='permissive',
        patient_consent_required=False,
        patient_notification_required=True,
        patient_may_refuse=None,
        prescriber_override="Sign the 'Dispense as written' line (two-line form); Medicaid/CHIP/Medicare fills: substitution mandatory at lower price absent 'Brand Medically Necessary' in own writing",
        statute_citation='Ind. Code §§ 16-42-22-6 to -10',
        statute_url='https://law.justia.com/codes/indiana/title-16/article-42/chapter-22/',
        as_of='2026-08-14',
    ),
    StateRule(
        state='IA',
        name='Iowa',
        substitution='permissive',
        patient_consent_required=False,
        patient_notification_required=None,
        patient_may_refuse=None,
        prescriber_override="'Dispense as written' indicated on the prescription",
        statute_citation='Iowa Code § 155A.32 (2024)',
        statute_url='https://www.legis.iowa.gov/docs/code/155A.32.pdf',
        as_of='2026-08-14',
    ),
    StateRule(
        state='KS',
        name='Kansas',
        substitution='permissive',
        patient_consent_required=False,
        patient_notification_required=False,
        patient_may_refuse=None,
        prescriber_override="'Dispense as written' on the prescription or in the oral order",
        statute_citation='K.S.A. § 65-1637',
        statute_url='https://www.ksrevisor.gov/statutes/chapters/ch65/065_016_0037.html',
        as_of='2026-08-14',
    ),
    StateRule(
        state='KY',
        name='Kentucky',
        substitution='mandatory',
        patient_consent_required=False,
        patient_notification_required=False,
        patient_may_refuse=True,
        prescriber_override="'Do Not Substitute' indicated in the manner of the prescriber's choice (may not be preprinted)",
        statute_citation='KRS § 217.822',
        statute_url='https://codes.findlaw.com/ky/title-xviii-public-health/ky-rev-st-sect-217-822.html',
        as_of='2026-08-14',
    ),
    StateRule(
        state='LA',
        name='Louisiana',
        substitution='permissive',
        patient_consent_required=True,
        patient_notification_required=True,
        patient_may_refuse=True,
        prescriber_override="Written: handwritten mark in the 'Dispense as Written'/'DAW' checkbox plus manual signature; oral: name the brand; electronic: DAW/BMN indication",
        statute_citation='La. R.S. § 37:1241(A)(17); LAC 46:LIII.2517',
        statute_url='https://www.law.cornell.edu/regulations/louisiana/La-Admin-Code-tit-46-SS-LIII-2517',
        as_of='2026-08-14',
    ),
    StateRule(
        state='ME',
        name='Maine',
        substitution='mandatory',
        patient_consent_required=False,
        patient_notification_required=True,
        patient_may_refuse=True,
        prescriber_override="Handwritten check mark in the lower-right box, or handwrite and sign 'dispense as written'/'DAW'/'brand'/'brand necessary'/'brand medically necessary'",
        statute_citation='32 M.R.S. § 13781',
        statute_url='https://legislature.maine.gov/statutes/32/title32sec13781.html',
        as_of='2026-08-14',
    ),
    StateRule(
        state='MD',
        name='Maryland',
        substitution='permissive',
        patient_consent_required=False,
        patient_notification_required=True,
        patient_may_refuse=None,
        prescriber_override='Prescriber states expressly that the prescription is to be dispensed only as directed (no fixed magic words)',
        statute_citation='Md. Code, Health Occ. § 12-504',
        statute_url='https://mgaleg.maryland.gov/mgawebsite/Laws/StatuteText?article=gho&section=12-504&enactments=false',
        as_of='2026-08-14',
    ),
    StateRule(
        state='MA',
        name='Massachusetts',
        substitution='mandatory',
        patient_consent_required=False,
        patient_notification_required=False,
        patient_may_refuse=False,
        prescriber_override="Mark the prescription 'no substitution' per the DPH format and validate by signing (cannot be a preset default)",
        statute_citation='Mass. Gen. Laws ch. 112, § 12D',
        statute_url='https://malegislature.gov/Laws/GeneralLaws/PartI/TitleXVI/Chapter112/Section12D',
        as_of='2026-08-14',
    ),
    StateRule(
        state='MI',
        name='Michigan',
        substitution='permissive',
        patient_consent_required=False,
        patient_notification_required=True,
        patient_may_refuse=None,
        prescriber_override="Handwrite 'dispense as written' or 'd.a.w.' on the signed prescription or in the box adjacent to the preprinted statement; non-written: express indication",
        statute_citation='MCL § 333.17755',
        statute_url='https://www.legislature.mi.gov/Laws/MCL?objectName=mcl-333-17755',
        as_of='2026-08-14',
    ),
    StateRule(
        state='MN',
        name='Minnesota',
        substitution='mandatory',
        patient_consent_required=False,
        patient_notification_required=True,
        patient_may_refuse=True,
        prescriber_override="Personally handwrite 'dispense as written' or 'D.A.W.'; e-prescription individual DAW designation plus e-signature; oral express statement",
        statute_citation='Minn. Stat. § 151.21',
        statute_url='https://www.revisor.mn.gov/statutes/cite/151.21',
        as_of='2026-08-14',
    ),
    StateRule(
        state='MS',
        name='Mississippi',
        substitution='mandatory',
        patient_consent_required=False,
        patient_notification_required=True,
        patient_may_refuse=True,
        prescriber_override='Product selection expressly prohibited by the prescriber (no fixed statutory phrase)',
        statute_citation='Miss. Code Ann. § 73-21-117',
        statute_url='https://codes.findlaw.com/ms/title-73-professions-and-vocations/ms-code-sect-73-21-117.html',
        as_of='2026-08-14',
    ),
    StateRule(
        state='MO',
        name='Missouri',
        substitution='permissive',
        patient_consent_required=False,
        patient_notification_required=False,
        patient_may_refuse=True,
        prescriber_override="'Brand medically necessary', 'dispense as written', 'do not substitute', 'DAW', or words of similar import; oral instruction",
        statute_citation='Mo. Rev. Stat. § 338.056',
        statute_url='https://revisor.mo.gov/main/OneSection.aspx?section=338.056',
        as_of='2026-08-14',
    ),
    StateRule(
        state='MT',
        name='Montana',
        substitution='permissive',
        patient_consent_required=False,
        patient_notification_required=True,
        patient_may_refuse=True,
        prescriber_override="Prescriber certifies the brand is 'medically necessary for that particular patient' (written; oral must be express)",
        statute_citation='Mont. Code Ann. § 37-7-505',
        statute_url='https://mca.legmt.gov/bills/mca/title_0370/chapter_0070/part_0050/section_0050/0370-0070-0050-0050.html',
        as_of='2026-08-14',
    ),
    StateRule(
        state='NE',
        name='Nebraska',
        substitution='permissive',
        patient_consent_required=False,
        patient_notification_required=False,
        patient_may_refuse=True,
        prescriber_override="'Dispense as written'/'brand medically necessary'/'no drug product selection' or D.A.W./B.M.N./N.D.P.S.; oral noted",
        statute_citation='Neb. Rev. Stat. § 38-28,111',
        statute_url='https://nebraskalegislature.gov/laws/statutes.php?statute=38-28,111',
        as_of='2026-08-14',
    ),
    StateRule(
        state='NV',
        name='Nevada',
        substitution='mandatory',
        patient_consent_required=False,
        patient_notification_required=True,
        patient_may_refuse=True,
        prescriber_override="Handwritten 'Dispense as Written' (preprinted disregarded), electronic DAW, or oral before dispensing; refusal right does not apply when a government agency pays",
        statute_citation='Nev. Rev. Stat. § 639.2583',
        statute_url='https://www.leg.state.nv.us/NRS/NRS-639.html#NRS639Sec2583',
        as_of='2026-08-14',
    ),
    StateRule(
        state='NH',
        name='New Hampshire',
        substitution='permissive',
        patient_consent_required=False,
        patient_notification_required=False,
        patient_may_refuse=None,
        prescriber_override="Handwritten 'medically necessary' on each paper prescription; electronic indication; oral instruction",
        statute_citation='N.H. Rev. Stat. Ann. § 318:47-d',
        statute_url='https://gc.nh.gov/rsa/html/XXX/318/318-47-d.htm',
        as_of='2026-08-14',
    ),
    StateRule(
        state='NJ',
        name='New Jersey',
        substitution='mandatory',
        patient_consent_required=False,
        patient_notification_required=False,
        patient_may_refuse=True,
        prescriber_override="Prescriber initials next to 'do not substitute'; oral: states it",
        statute_citation='N.J. Stat. Ann. § 24:6E-7',
        statute_url='https://codes.findlaw.com/nj/title-24-food-and-drugs/nj-st-sect-24-6e-7/',
        as_of='2026-08-14',
    ),
    StateRule(
        state='NM',
        name='New Mexico',
        substitution='permissive',
        patient_consent_required=False,
        patient_notification_required=False,
        patient_may_refuse=None,
        prescriber_override="Electronically accessible entry 'no substitution'/'no sub' on the prescription",
        statute_citation='N.M. Stat. Ann. § 26-3-3',
        statute_url='https://codes.findlaw.com/nm/chapter-26-drugs-and-cosmetics/nm-st-sect-26-3-3/',
        as_of='2026-08-14',
    ),
    StateRule(
        state='NY',
        name='New York',
        substitution='mandatory',
        patient_consent_required=False,
        patient_notification_required=False,
        patient_may_refuse=False,
        prescriber_override="Prescriber handwrites 'daw' in the box (no other letters or marks; no preprinting) or gives an electronic DAW direction",
        statute_citation='N.Y. Educ. Law §§ 6810(6), 6816-a',
        statute_url='https://www.nysenate.gov/legislation/laws/EDN/6816-A',
        as_of='2026-08-14',
    ),
    StateRule(
        state='NC',
        name='North Carolina',
        substitution='permissive',
        patient_consent_required=False,
        patient_notification_required=False,
        patient_may_refuse=None,
        prescriber_override="Sign the 'Dispense as Written' line on the two-line form; handwritten DAW; oral (narrow-therapeutic-index refills need documented prescriber AND patient consent)",
        statute_citation='N.C. Gen. Stat. § 90-85.28',
        statute_url='https://www.ncleg.gov/EnactedLegislation/Statutes/HTML/BySection/Chapter_90/GS_90-85.28.html',
        as_of='2026-08-14',
    ),
    StateRule(
        state='ND',
        name='North Dakota',
        substitution='permissive',
        patient_consent_required=False,
        patient_notification_required=True,
        patient_may_refuse=True,
        prescriber_override="Prescriber's own handwriting 'brand medically necessary'; oral express; e-prescription requires a specific overt action",
        statute_citation='N.D. Cent. Code § 19-02.1-14.1',
        statute_url='https://codes.findlaw.com/nd/title-19-foods-drugs-oils-and-compounds/nd-cent-code-sect-19-02-1-14-1/',
        as_of='2026-08-14',
    ),
    StateRule(
        state='OH',
        name='Ohio',
        substitution='permissive',
        patient_consent_required=False,
        patient_notification_required=True,
        patient_may_refuse=True,
        prescriber_override="Handwrite or actively display 'dispense as written', 'D.A.W.', 'do not substitute', 'brand medically necessary' (never preprinted or stamped); oral 'medically necessary'",
        statute_citation='Ohio Rev. Code § 4729.38',
        statute_url='https://codes.ohio.gov/ohio-revised-code/section-4729.38',
        as_of='2026-08-14',
    ),
    StateRule(
        state='OK',
        name='Oklahoma',
        substitution='permissive',
        patient_consent_required=True,
        patient_notification_required=None,
        patient_may_refuse=True,
        prescriber_override="Substitution requires the authority of the prescriber or the purchaser; Medicaid requires 'brand necessary' certification",
        statute_citation='59 Okla. Stat. § 353.24(B)(4)',
        statute_url='https://law.justia.com/codes/oklahoma/title-59/section-59-353-24/',
        as_of='2026-08-14',
    ),
    StateRule(
        state='OR',
        name='Oregon',
        substitution='permissive',
        patient_consent_required=False,
        patient_notification_required=False,
        patient_may_refuse=True,
        prescriber_override='Written, telephonic, or electronic statement that there may be no substitution for the specified brand name drug',
        statute_citation='Or. Rev. Stat. § 689.515',
        statute_url='https://oregon.public.law/statutes/ors_689.515',
        as_of='2026-08-14',
    ),
    StateRule(
        state='PA',
        name='Pennsylvania',
        substitution='mandatory',
        patient_consent_required=False,
        patient_notification_required=True,
        patient_may_refuse=True,
        prescriber_override="Handwritten 'brand necessary' or 'brand medically necessary'; oral express",
        statute_citation='35 Pa. Stat. § 960.3',
        statute_url='https://codes.findlaw.com/pa/title-35-ps-health-and-safety/pa-st-sect-35-960-3/',
        as_of='2026-08-14',
    ),
    StateRule(
        state='RI',
        name='Rhode Island',
        substitution='mandatory',
        patient_consent_required=False,
        patient_notification_required=False,
        patient_may_refuse=True,
        prescriber_override="Prescriber orders 'brand name necessary' on the form or gives oral direction; patient refusal must be in writing",
        statute_citation='R.I. Gen. Laws § 5-19.1-19',
        statute_url='https://webserver.rilegislature.gov/Statutes/TITLE5/5-19.1/5-19.1-19.htm',
        as_of='2026-08-14',
    ),
    StateRule(
        state='SC',
        name='South Carolina',
        substitution='permissive',
        patient_consent_required=True,
        patient_notification_required=True,
        patient_may_refuse=True,
        prescriber_override="Sign the 'DISPENSE AS WRITTEN' line on the two-signature-line form (invalid without a signature on one line); oral equivalent",
        statute_citation='S.C. Code §§ 39-24-30, 39-24-40',
        statute_url='https://www.scstatehouse.gov/code/t39c024.php',
        as_of='2026-08-14',
    ),
    StateRule(
        state='SD',
        name='South Dakota',
        substitution='permissive',
        patient_consent_required=False,
        patient_notification_required=True,
        patient_may_refuse=True,
        prescriber_override="Handwritten 'brand necessary' or similar (not preprinted or stamped)",
        statute_citation='S.D. Codified Laws §§ 36-11-46.1 to -46.3',
        statute_url='https://sdlegislature.gov/api/Statutes/36-11-46.1.html',
        as_of='2026-08-14',
    ),
    StateRule(
        state='TN',
        name='Tennessee',
        substitution='mandatory',
        patient_consent_required=False,
        patient_notification_required=False,
        patient_may_refuse=True,
        prescriber_override='Prescriber notes the medical necessity of the brand per § 53-10-204; patient may demand the brand and pay the difference',
        statute_citation='Tenn. Code Ann. § 53-10-205',
        statute_url='https://codes.findlaw.com/tn/title-53-food-drugs-and-cosmetics/tn-code-sect-53-10-205/',
        as_of='2026-08-14',
    ),
    StateRule(
        state='TX',
        name='Texas',
        substitution='permissive',
        patient_consent_required=True,
        patient_notification_required=True,
        patient_may_refuse=True,
        prescriber_override="Prescriber certifies brand medically necessary per the § 562.015 dispensing directive ('brand necessary'/'brand medically necessary')",
        statute_citation='Tex. Occ. Code §§ 562.008, 562.009',
        statute_url='https://statutes.capitol.texas.gov/Docs/OC/htm/OC.562.htm',
        as_of='2026-08-14',
    ),
    StateRule(
        state='UT',
        name='Utah',
        substitution='permissive',
        patient_consent_required=True,
        patient_notification_required=True,
        patient_may_refuse=True,
        prescriber_override="Write 'dispense as written' or sign the preprinted DAW line; oral prohibition noted by the pharmacist",
        statute_citation='Utah Code § 58-17b-605',
        statute_url='https://le.utah.gov/xcode/Title58/Chapter17B/58-17b-S605.html',
        as_of='2026-08-14',
    ),
    StateRule(
        state='VT',
        name='Vermont',
        substitution='mandatory',
        patient_consent_required=False,
        patient_notification_required=True,
        patient_may_refuse=True,
        prescriber_override='Prescriber instructs otherwise (no specific wording formality); patient refusing pays the price difference',
        statute_citation='18 V.S.A. § 4605',
        statute_url='https://legislature.vermont.gov/statutes/section/18/091/04605',
        as_of='2026-08-14',
    ),
    StateRule(
        state='VA',
        name='Virginia',
        substitution='permissive',
        patient_consent_required=False,
        patient_notification_required=True,
        patient_may_refuse=True,
        prescriber_override="'Brand medically necessary' specified on the prescription; oral dispensing instructions followed",
        statute_citation='Va. Code § 54.1-3408.03',
        statute_url='https://law.lis.virginia.gov/vacode/title54.1/section54.1-3408.03/',
        as_of='2026-08-14',
    ),
    StateRule(
        state='WA',
        name='Washington',
        substitution='mandatory',
        patient_consent_required=False,
        patient_notification_required=False,
        patient_may_refuse=True,
        prescriber_override="Prescriber signs the 'DISPENSE AS WRITTEN' line on the two-line form; out-of-state: the words 'dispense as written'",
        statute_citation='RCW 69.41.120, 69.41.130',
        statute_url='https://app.leg.wa.gov/RCW/default.aspx?cite=69.41.130',
        as_of='2026-08-14',
    ),
    StateRule(
        state='WV',
        name='West Virginia',
        substitution='mandatory',
        patient_consent_required=False,
        patient_notification_required=True,
        patient_may_refuse=True,
        prescriber_override="Prescriber's own handwriting 'Brand Medically Necessary'; verbal noted on the file copy",
        statute_citation='W. Va. Code § 30-5-12b',
        statute_url='https://code.wvlegislature.gov/30-5-12b/',
        as_of='2026-08-14',
    ),
    StateRule(
        state='WI',
        name='Wisconsin',
        substitution='mandatory',
        patient_consent_required=False,
        patient_notification_required=True,
        patient_may_refuse=True,
        prescriber_override="'No substitutions' / 'N.S.' on the face of the prescription or electronically (no preprinting)",
        statute_citation='Wis. Stat. § 450.13',
        statute_url='https://docs.legis.wisconsin.gov/statutes/statutes/450/13',
        as_of='2026-08-14',
    ),
    StateRule(
        state='WY',
        name='Wyoming',
        substitution='permissive',
        patient_consent_required=False,
        patient_notification_required=None,
        patient_may_refuse=None,
        prescriber_override="Prescriber clearly indicates substitution is not permitted; oral prohibition followed up in writing 'brand medically necessary' (2017 SF0121 changed shall to may)",
        statute_citation='Wyo. Stat. §§ 33-24-148, 33-24-149',
        statute_url='https://www.wyoleg.gov/Legislation/2017/SF0121',
        as_of='2026-08-14',
    ),
)

_BY_STATE: dict[str, StateRule] = {rule.state: rule for rule in STATE_RULES}


def rule_for(state: str) -> StateRule | None:
    return _BY_STATE.get(state.strip().upper())


def statelaw_payload() -> dict[str, Any]:
    return {
        "disclaimer": DISCLAIMER,
        "states": [asdict(rule) for rule in STATE_RULES],
    }
